buildscript {
    repositories {
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }

        mavenCentral()

        gradlePluginPortal()
    }

    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.24'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'

group = 'com.sosnitzka'
archivesBaseName = 'taiga'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')

            mods {
                taiga {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            mods {
                taiga {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }

    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com/'
    }

    maven {
        name = 'CurseMaven'
        url = 'https://cursemaven.com/'
    }

    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.5'

    compileOnly fg.deobf(
        'curse.maven:mantle-74924:7563777'
    )

    compileOnly fg.deobf(
        'curse.maven:tinkers-construct-74072:7449219'
    )
}

sourceSets {
    main {
        resources {
            srcDir 'src/main/resources'
        }
    }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    inputs.property 'version', project.version
    inputs.property 'mcversion', '1.20.1'

    filesMatching('META-INF/mods.toml') {
        expand(
            version: project.version,
            mcversion: '1.20.1'
        )
    }
}

jar {
    manifest {
        attributes(
            'Specification-Title': 'taiga',
            'Specification-Vendor': 'sosnitzka',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'sosnitzka'
        )
    }
}

tasks.named('jar') {
    finalizedBy('reobfJar')
}
